class Location():

    def __init__(self):
        self.lst=['aleta wondo or yirgalem',
 'gambela',
 'worabe and wolayita sodo',
 'british embassy',
 'bahir dar district',
 'the embassy of canada to ethiopia',
 'meki',
 'dansha',
 'gereb giba',
 'shashemene',
 'mekelle',
 'dubai',
 'woliso',
 'bole medhanialem',
 'bisrate gabriel',
 'welliso',
 'north shoa zone',
 'guba',
 'asella district',
 'bule hora',
 'bob marley square',
 'snnpr',
 'ethiopian aviation academy',
 'harer',
 'alfoz plaza',
 'sebeta',
 'mehal meda',
 'amhara',
 'dilla',
 'zeway',
 'hawassa and dredawa',
 'jigjiga & wolkite',
 'united arab emirates',
 'nekemt',
 'sidama',
 'gode',
 'old airport',
 'bahir dar',
 'sodo',
 'nekemet',
 'diredawa',
 'gondar',
 'bahardar',
 'merawi',
 'metu oromia',
 'goro ict park',
 'burie',
 'tigray',
 'gereb',
 'shashamane district',
 'ticho',
 'bisrate gebriel',
 'galan',
 'logia',
 'ethiopian airlines head office',
 'somali',
 'ayertena',
 'kilnto',
 'jimma',
 '#addis ababa',
 'south nations nationalities and peoples region',
 'bishoftu',
 'dukem',
 'butajira',
 'shambu',
 'gelan',
 'finoteselam amhara',
 'sekota',
 'saris',
 'ethiopian airport enterprise building',
 'kality',
 'welliso and fitche.',
 'debre sina',
 'ketema',
 'nifas silk lafto',
 'gudina',
 'hossaena',
 'dire dawa and bahir dar',
 'ayat',
 'doba building',
 'commercial building',
 'dire dawa',
 'adama',
 'arert',
 'jimma district',
 'bishoftuoromia',
 'bale district',
 'wolaita sodo',
 'hummera and shiraro',
 'oromia',
 'harari',
 'worabe',
 'melkadida',
 'fitcheoromia',
 'hawassa',
 'shimelba',
 'may tseberi',
 'hummera',
 'giba',
 'assosa',
 'gerji',
 'liben and gumi eldalo',
 'mojo',
 'hegere mariam woreda',
 'finfinne district',
 'imi',
 'debrezeit',
 'wolkite',
 'guagua',
 'pugnido refugee camp',
 'benishangul gumuz',
 'yirgalem',
 'arbaminch',
 'addis-ababa',
 'administration',
 'ethiopian skylight hotel',
 'sire',
 'ethiopian airlines head quarter',
 'dessie',
 'gambella',
 'dangla',
 'emdeber',
 'ambo',
 'bahr dar',
 'debrebrhan',
 'hawasa',
 'hawassa district',
 'wolkite project',
 'adamma',
 'guangua',
 'shiraro',
 'west hararghe',
 'dera',
 'addis ababa',
 'adama district',
 'ethiopian airports building',
 'gunchire',
 'ayat on the road to tafo',
 'alem',
 'asella',
 'wolayita',
 'shashemani',
 'kazanchis',
 'semera',
 'abomsa',
 'dimma',
 'hossana',
 'chiro',
 'chiro district',
 'jigjiga',
 'wolaita',
 'kobe',
 'debre tabor']

    def GiveLocation(self):
        return self.lst
    

test=Location().GiveLocation()
print(test)